# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1814e6826f73548bdeac74e3a65840b058d396f2fb823d4cbd697713575b8760b8034e049e426850930506fe3acf2ec0f66db2c782ef13ac717068718ed3d187

test:
  secret_key_base: 5a0bd65fe1f96dd03e146fbf1fa1caa04ad3db98a944af774df95963f2e30271583cba0481717f0339e9d52dcc5c27ef071d55711789846f7365770784f211c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
